"""choose welcome message


Revision ID: d3aa446b4ade
Revises: 873a511b6c46
Create Date: 2020-10-01 21:29:45.761884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3aa446b4ade'
down_revision = '873a511b6c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('welcome', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'welcome')
    # ### end Alembic commands ###
